Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,41 +1,39 @@
 name: Build Flutter APK
-on:
-  workflow_dispatch:
-  push:
-    branches:
-      - main
-      
+
+on: [push, workflow_dispatch]
+
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download project
-        uses: actions/checkout@v4
-      - name: Install Flutter
-        uses: subosito/flutter-action@v2
-        with:
-          flutter-version: '3.35.2'
-          channel: stable
-          cache: true
-          
-  - name: Check Flutter projec
+build:
+runs-on: ubuntu-latest
+steps:
+- name: Download project
+uses: actions/checkout@v4
+
+  - name: Install Flutter
+    uses: subosito/flutter-action@v2
+    with:
+      flutter-version: '3.35.2'
+      channel: stable
+      cache: true
+
+  - name: Check Flutter project
     run: |
-          if [ ! -f pubspec.yaml ]; then
-            echo "ERROR: pubspec.yaml not found in the repository root"
-            exit 1
-        fi
+      if [ ! -f pubspec.yaml ]; then
+        echo "ERROR: pubspec.yaml not found in the repository root"
+        exit 1
+      fi
 
-      - name: Install dependencies
-        run: flutter pub get
+  - name: Install dependencies
+    run: flutter pub get
 
-      - name: Analyze project
-        run: flutter analyze
+  - name: Analyze project
+    run: flutter analyze
 
-      - name: Build APK
-        run: flutter build apk --release
+  - name: Build APK
+    run: flutter build apk --release
 
-      - name: Upload APK
-        uses: actions/upload-artifact@v4
-        with:
-          name: al-saadi-lite-apk
-          path: build/app/outputs/flutter-apk/app-release.apk
+  - name: Upload APK
+    uses: actions/upload-artifact@v4
+    with:
+      name: al-saadi-lite-apk
+      path: build/app/outputs/flutter-apk/app-release.apk
